### ISSUE TITLE
Unable to Run Files

### ISSUE THREAD

**Issue by scut-shpan** [MrSecant/GaussianGrasper#3]
I am writing to seek assistance as I am unable to successfully run any files. Despite having installed all the necessary requirements and downloading the dataset, I am encountering issues that prevent successful execution.

For instance, I received the following error message:

No such file or directory: '/share/home/HCI/shaohui/datasets/GaussianGrasper_datasets/real_world_paper/data_collection/scene_0001/boundary_mask/'
It appears that the directory does not exist or is not accessible. Additionally, I am unable to locate the 'ns-train' executable or similar scripts that should be part of the setup.

I am hoping to receive a reply from you with guidance on how to resolve these issues. Your prompt attention to this matter would be greatly appreciated.

Thank you for your time and assistance.

**Comment by MrSecant** [comment]
1.“Boundary_mask” is a npy file representing the valid region in each image. For example, in our data, we use this to make the training process focus on the tabletop and ignore the background (such as the wall). 

2."ns-train" is the command of nerfstudio, you can also use the training file "nerfstudio/scripts/train.py". The installation of nerfstudio is shown in the repo. And you can follow the instruction the Nerfstudio repo as well.

3. Thanks for your reminding, we have not released the code of CLIP feature extraction. The will be available soon.

**Comment by scut-shpan** [comment]
Thanks for your detailed explanation.

**Comment by Xiong5Heng** [comment]
> n

Hello, have you resolved the problem and launched a demo successfully?  Can you share your experience? Contact me if you'd like (xiong.heng7@gmail.com).

**Comment by z-x-j** [comment]
> Thanks for your detailed explanation.

请问怎么生成boundary_mask？感谢
